<?php

return [
    'trial_days' => (int) env('STRIPE_TRIAL_DAYS', 14),

    'plans' => [
        'starter' => [
            'slug' => 'starter',
            'name' => 'Starter',
            'price' => 29,
            'stripe_price_id' => env('STRIPE_STARTER_PRICE_ID'),
            'recommended' => false,
            'features' => [
                'online_booking',
                'booking_diary',
                'tables',
                'email_confirmations',
                'basic_settings',
            ],
            'staff_limit' => 3,
            'feature_list' => [
                'Online booking form',
                'Booking diary',
                'Table and area management',
                'Email confirmations',
                'Basic venue settings',
                'Up to 3 staff users',
            ],
        ],
        'professional' => [
            'slug' => 'professional',
            'name' => 'Professional',
            'price' => 59,
            'stripe_price_id' => env('STRIPE_PROFESSIONAL_PRICE_ID'),
            'recommended' => true,
            'features' => [
                'online_booking',
                'booking_diary',
                'tables',
                'email_confirmations',
                'basic_settings',
                'customer_crm',
                'advanced_booking_rules',
                'analytics',
                'reporting',
                'enhanced_branding',
            ],
            'staff_limit' => 10,
            'feature_list' => [
                'Everything in Starter',
                'Customer CRM and notes',
                'Advanced booking rules',
                'Analytics and reporting',
                'Enhanced branding controls',
                'Up to 10 staff users',
            ],
        ],
        'premium' => [
            'slug' => 'premium',
            'name' => 'Premium',
            'price' => 99,
            'stripe_price_id' => env('STRIPE_PREMIUM_PRICE_ID'),
            'recommended' => false,
            'features' => [
                'online_booking',
                'booking_diary',
                'tables',
                'email_confirmations',
                'basic_settings',
                'customer_crm',
                'advanced_booking_rules',
                'analytics',
                'reporting',
                'enhanced_branding',
                'priority_support',
                'advanced_reporting',
                'waitlist',
                'advanced_service_controls',
                'unlimited_staff',
            ],
            'staff_limit' => null,
            'feature_list' => [
                'Everything in Professional',
                'Priority support indicator',
                'Advanced reporting',
                'Waitlist-ready premium modules',
                'Advanced multi-service controls',
                'Unlimited staff users',
            ],
        ],
    ],

    'features' => [
        'online_booking' => ['name' => 'Online booking', 'required_plan' => 'starter'],
        'booking_diary' => ['name' => 'Booking diary', 'required_plan' => 'starter'],
        'tables' => ['name' => 'Tables and areas', 'required_plan' => 'starter'],
        'email_confirmations' => ['name' => 'Email confirmations', 'required_plan' => 'starter'],
        'basic_settings' => ['name' => 'Basic settings', 'required_plan' => 'starter'],
        'customer_crm' => ['name' => 'Customer CRM', 'required_plan' => 'professional'],
        'staff_limit_professional' => ['name' => 'More staff seats', 'required_plan' => 'professional'],
        'advanced_booking_rules' => ['name' => 'Advanced booking rules', 'required_plan' => 'professional'],
        'analytics' => ['name' => 'Analytics', 'required_plan' => 'professional'],
        'reporting' => ['name' => 'Reporting', 'required_plan' => 'professional'],
        'enhanced_branding' => ['name' => 'Enhanced branding', 'required_plan' => 'professional'],
        'priority_support' => ['name' => 'Priority support', 'required_plan' => 'premium'],
        'advanced_reporting' => ['name' => 'Advanced reporting', 'required_plan' => 'premium'],
        'waitlist' => ['name' => 'Waitlist', 'required_plan' => 'premium'],
        'advanced_service_controls' => ['name' => 'Advanced multi-service controls', 'required_plan' => 'premium'],
        'unlimited_staff' => ['name' => 'Unlimited staff users', 'required_plan' => 'premium'],
    ],
];
